# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.pc-incubator
canonical: http://hl7.org/fhir/uv/pc-incubator
name: Patient Care Incubator
title: FHIR R6 Patient Care Incubator
description: The Incubator for resources being further developed by Patient Care for the FHIR R6 release
status: active
version: 0.1.0
fhirVersion: 6.0.0-ballot3
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 International / Patient Care
  url: http://www.hl7.org/Special/committees/patientcare
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pc

dependencies:

parameters:
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  show-inherited-invariants: false
  shownav: false
  path-pages:
    - input/pagecontent
  path-resource: 
    - input/resources/clinicalassessment
    - input/resources/conditiondefinition
    - input/resources/linkage
  special-url-base: http://hl7.org/fhir
  additional-resource: 
    - input/resources/clinicalassessment/StructureDefinition-ClinicalAssessment.xml
    - input/resources/conditiondefinition/StructureDefinition-ConditionDefinition.xml
    - input/resources/linkage/StructureDefinition-Linkage.xml

resources:
  Linkage/example:
    name: linkage-example
    description: An example of a Linkage resource that links two resources together.
  ClinicalAssessment/example:
    name: assessment-example
  List/ClinicalAssessment-examples:
    description: A list of examples of the ClinicalAssessment resource.
  List/ConditionDefinition-examples:
    description: A list of examples of the ConditionDefinition resource.
  List/Linkage-examples:
    description: A list of examples of the Linkage resource.

pages:
  index.md:
    title: Patient Care Incubator
  changes.md:
    title: Change Log

menu:
  Home: index.html
  Artifacts: artifacts.html
  Change Log: changes.html
